title: Front Commerce
subtitle: Using Front Commerce
versions:
  - "1"
sidebar_categories:
  null:
    - docs/index
  Essentials:
    - docs/essentials/installation
    - docs/essentials/extend-the-theme
    - docs/essentials/adapt-theme-to-your-brand
    - docs/essentials/create-a-ui-component
    - docs/essentials/add-component-to-storybook
    - docs/essentials/add-a-page-client-side
  Advanced:
    - GraphQL:
        - docs/advanced/graphql/overview
    - Theme:
        - docs/advanced/theme/overview
        - docs/advanced/theme/route-dispatcher
    - Checkout:
        - docs/advanced/checkout/overview
    - Performance:
        - docs/advanced/performance/overview
    - Server:
        - docs/advanced/server/overview
    - Production ready:
        - docs/advanced/production-ready/overview
  Concepts:
    - docs/concepts/create-business
  Magento2:
    - docs/magento2/what
  Reference:
    - docs/reference/api
  Appendices:
    - docs/appendices/roadmap
    - docs/appendices/migration-guides
    - docs/appendices/changelog

github_repo: front-commerce/developers.front-commerce.com

nav_links:
  "Home":
    url: /
  "Docs":
    url: /docs/
  "Help":
    url: /help.html
  "License":
    url: /license.html
  "Blog":
    url: /blog/

community_links:
  "Slack":
    url: "https://join.slack.com/t/front-commerce/shared_invite/enQtMzI2OTEyMDYzOTkxLWY0Y2JjYmRmNGQ2MWM1NzQyMjQwNzlmYzJmYzgzNTIwYzQ3MDVkMWZiYmYwNWFhODhmYWM5OTI4YjdiZDJkY2Q"
  "Twitter":
    url: "https://twitter.com/Front_Commerce"
  "Contact":
    url: "mailto:contact@front-commerce.com"

url: https://developers.front-commerce.com/
root: /
permalink: blog/:year/:month/:day/:title/

public_dir: public/
